### PR TITLE
fix required params parsing for routes with multiple paths and multiple params

### LINKED ISSUE #1267: Multiple path params with multiple paths leads to unnecessary required params
**Describe the bug**
When using multiple paths for a single endpoint, if any of the paths have a path param that is not contained in another path, all of the paths will contain that param and be marked as "required".

**To Reproduce**
Use the [example from the README](https://github.com/swaggo/swag#add-multiple-paths) to generate API specs. The generated spec will mark `group_id` as required for both paths.

**Expected behavior**
Paths that do not contain a path param will have that path param omitted in the generated spec.

**Your swag version**
v1.8.3

**Your go version**
go1.18.4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4

### PR DESCRIPTION
**Pull request by Phenix66**
**Describe the PR**
Fixes #1267 

**Relation issue**
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1267)

**Additional context**

### CODE REVIEW

File: parser.go [hunk 1]
```diff
@@ -975,7 +975,21 @@ func processRouterOperation(parser *Parser, operation *Operation) error {
 			parser.debug.Printf("warning: %s\n", err)
 		}
 
-		*op = &operation.Operation
+		if len(operation.RouterProperties) > 1 {
+			newOp := *operation
+			validParams := []spec.Parameter{}
```
Comment (ubogdan) [inline parser.go:980]: Please use `var validParams []spec.Parameter` in order to avoid mem allocations.

**Review by ubogdan — CHANGES_REQUESTED** [review]

File: parser.go (hunk 1 above)
Comment (Phenix66) [reply parser.go]: Updated

**Review by ubogdan — APPROVED** [review]

**Comment by ubogdan** [comment]
@Phenix66 Thanks for your contribution
