### PR TITLE
change the condition for checking custom arrayType

### LINKED ISSUE #558: 'swaggertype' tag doesn't work properly for pointer fields
**Describe the bug**
Swag output file looks very odd for the pointer fields having 'swaggertype' tag set to 'primitive,string'.
I expect same output for both pointer and embedded struct fields.
Also in case of wrong usage of 'swaggertype' or 'example' tag I'd like to see some warnings in the console output instead of 'silent' ignore them from output.

**To Reproduce**
Use source below and run `swag init`

GoLang source:
```
package main

// @summary
// @description
// @router /v1/a [post]
// @success 200 {object} Wrapper just a test
func handler() {
}

type Wrapper struct {
	A1 Person  `swaggertype:"primitive,string" example:"John Doe"`
	A2 *Person `swaggertype:"primitive,string" example:"John Doe"`
	A3 Person  `swaggertype:"string" example:"John Doe"`
	A4 *Person `swaggertype:"string" example:"John Doe"`
	A5 Person  `swaggertype:"primitive,string"`
	A6 *Person `swaggertype:"primitive,string"`
	A7 Person  `swaggertype:"string"`
	A8 *Person `swaggertype:"string"`
	A9 Person  `example:"John Doe"`
	AA *Person `example:"John Doe"`
	AB Person
	AC *Person
}

type Person struct {
	FirstName string
	LastName string
}

// @BasePath /
func main() {
}
```
Generated json & yaml files have same issue, so pasting here only yaml output
Resulting yaml:
```
basePath: /
definitions:
  main.Person:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    type: object
  main.Wrapper:
    properties:
      a1:  
        example: John Doe
        type: string
      a2: 
        properties:
          firstName:
            type: string
          lastName:
            type: string
        type: object
      a5:
        type: string
      a6:
        properties:
          firstName:
            type: string
          lastName:
            type: string
        type: object
      ab:
        $ref: '#/definitions/main.Person'
        type: object
      ac:
        $ref: '#/definitions/main.Person'
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/a:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Wrapper'
swagger: "2.0"
```

**Expected behavior**
```
basePath: /
definitions:
  main.Person:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    type: object
  main.Wrapper:
    properties:
      a1:
        example: John Doe
        type: string
      a2:
        example: John Doe
        type: string
      a5:
        type: string
      a6:
        type: string
      ab:
        $ref: '#/definitions/main.Person'
        type: object
      ac:
        $ref: '#/definitions/main.Person'
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/a:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Wrapper'
swagger: "2.0"
```
For the rest of the missed fields (a3, a4, a7, a8, a9, aa) I'd like to see at least some warnings in the console output of `swag init` command

**Your swag version**
e.g. 1.6.3

**Your go version**
1.13.0

### PR DESCRIPTION
**Pull request by sdghchj**
**Describe the PR**
Change the condition for checking custom arrayType, only if arrayType is specified by flag `swaggertype` 

**Relation issue**
fix #558

### CODE REVIEW

File: parser.go [hunk 1]
```diff
@@ -862,6 +862,7 @@ func (parser *Parser) parseStructField(pkgName string, field *ast.Field) (map[st
 
 	structField, err := parser.parseField(field)
 	if err != nil {
+		Println(err)
```
Comment (easonlin404) [inline parser.go]: I guess you want to show error warning message here, right? 👍 Could you help fix to return an error there instead of ignoring it? 
As previously refactoring commits were not fixing well and I have also known that there were a few the same things in the code where not return an error. It's okay for this PR.

**Comment by easonlin404** [comment]
Rest LGTM

File: parser.go (hunk 1 above)
Comment (sdghchj) [reply parser.go]: yes. 
Modified, return error directly, no need to print there.

**Comment by easonlin404** [comment]
@sdghchj thanks for your contribution. 👍
