### PR TITLE
Conflicting package + struct name

### LINKED ISSUE #225: Conflicting package + struct name
**Describe the bug**
When there's 2 models (used in `@success` tags) only 1 can be used and the result is funky 

I've created a test scenario that demonstrates the problem 100x better than I can do in text, but the gist of it;

there's `package1` and there's `package2`, both contain api methods in their `api.go` file and both contain a `data` subpackage with a `Foo` struct.  
because swag only uses the top level package name everywhere these 2 `Foo` structs will conflict because they're both considered to be `data.Foo`.

as a result the api methods in both `package1` and `package2` will have the same `data.Foo` even though they should be different.  

to add a little extra funkiness, because the order on go's map is random, the resulting generated spec switches around between the 2 every time you generate it.

**To Reproduce**
see the test case: https://github.com/rubensayshi/swag/tree/conflicting-model-name-test-case/testdata/conflicting_model_name

**Your swag version**
master

### PR DESCRIPTION
**Pull request by wsnotify**
**Describe the PR**
If code uses two packages that contains types with same name, swag generate wrong json/yaml. This PR fixes this.

**Relation issue**
Fixes #225 

**Additional context**
This changes need testing on bigger swag files.

### CODE REVIEW

File: property_test.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func TestGetPropertyNameSelectorExpr(t *testing.T) {
 		"string",
 		"",
 	}
-	propertyName, err := getPropertyName(input, New())
+	propertyName, err := getPropertyName("test", input, New())
```
Comment (easonlin404) [inline property_test.go]: I guess you're testing it so hardcode "test" string, right? 😄

Comment (wsnotify) [reply property_test.go]: What do you suggest?

File: property.go [hunk 2]
```diff
@@ -126,24 +127,25 @@ func getPropertyName(expr ast.Expr, parser *Parser) (propertyName, error) {
...
+		return getArrayPropertyName(pkgName, elt.X, parser)
 	case *ast.SelectorExpr:
 		return parseFieldSelectorExpr(elt, parser, newArrayProperty)
 	case *ast.Ident:
-		name := TransToValidSchemeType(elt.Name)
+		name := fmt.Sprintf("%s.%s", pkgName, TransToValidSchemeType(elt.Name))
 		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[name]; isCustomType {
 			name = actualPrimitiveType
 		}
 		return propertyName{SchemaType: "array", ArrayType: name}
```
Comment (sdghchj) [inline property.go]: Need to add package name only when find in CustomPrimitiveTypes, same in default case.
```
name := TransToValidSchemeType(elt.Name)
if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
    name = actualPrimitiveType
}
return propertyName{SchemaType: "array", ArrayType: name}
```

**Comment by sdghchj** [comment]
Some optimizations. Take a look:
```
func getPropertyName(pkgName string,expr ast.Expr, parser *Parser) (propertyName, error) {
	switch tp := expr.(type) {
        case *ast.SelectorExpr:
		return parseFieldSelectorExpr(tp, parser, newProperty), nil
	case *ast.StarExpr:
		return getPropertyName(pkgName,tp.X, parser)
	case *ast.ArrayType:
		return getArrayPropertyName(pkgName,tp.Elt, parser), nil
	case *ast.MapType,*ast.StructType,*ast.InterfaceType:
		return propertyName{SchemaType: "object", ArrayType: "object"}, nil
	case *ast.Ident:
		name := tp.Name
		// check if it is a custom type
		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
			return propertyName{SchemaType: actualPrimitiveType, ArrayType: actualPrimitiveType}, nil
		}

		schemeType := TransToValidSchemeType(name)
		return propertyName{SchemaType: schemeType, ArrayType: schemeType}, nil
	default:
		return propertyName{}, errors.New("not supported" + fmt.Sprint(expr))
	}
}

func getArrayPropertyName(pkgName string, astTypeArrayElt ast.Expr, parser *Parser) propertyName {
	switch elt := astTypeArrayElt.(type) {
	case *ast.StructType, *ast.MapType, *ast.InterfaceType:
		return propertyName{SchemaType: "array", ArrayType: "object"}
	case *ast.ArrayType:
		return propertyName{SchemaType: "array", ArrayType: "array"}
	case *ast.StarExpr:
		return getArrayPropertyName(pkgName,elt.X, parser)
	case *ast.SelectorExpr:
		return parseFieldSelectorExpr(elt, parser, newArrayProperty)
	case *ast.Ident:
		name := TransToValidSchemeType(elt.Name)
		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
			name = actualPrimitiveType
		}
		return propertyName{SchemaType: "array", ArrayType: name}
	default:
		name := TransToValidSchemeType(fmt.Sprintf("%s", astTypeArrayElt))
		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
			name = actualPrimitiveType
		}
		return propertyName{SchemaType: "array", ArrayType: name}
	}
}

```

**Comment by wsnotify** [comment]
@sdghchj Good job! I used your code, but added `FuncType` part from original:
```
case *ast.FuncType:
	return propertyName{SchemaType: "func", ArrayType: ""}, nil
```
In current state code are passing tests.

**Comment by sdghchj** [comment]
What does FuncTyp works for? @wsnotify

File: property.go (hunk 2 above)
Comment (sdghchj) [reply property.go]: Sorry, review again and it is better as follows , I think , in case of redefinition of golang primitive types, for example 'type int32 string'
```
case *ast.Ident:
		name := elt.Name
		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
			name = actualPrimitiveType
		}else{
			name = TransToValidSchemeType(elt.Name)
		}
		return propertyName{SchemaType: "array", ArrayType: name}
	default:
		name := fmt.Sprintf("%s", astTypeArrayElt)
		if actualPrimitiveType, isCustomType := parser.CustomPrimitiveTypes[pkgName + "." + name]; isCustomType {
			name = actualPrimitiveType
		}else{
			name = TransToValidSchemeType(name)
		}
		return propertyName{SchemaType: "array", ArrayType: name}
```

**Comment by wsnotify** [comment]
> What does FuncTyp works for? @wsnotify

In master we have:
```
	if _, ok := expr.(*ast.FuncType); ok { // if func()
		return propertyName{SchemaType: "func", ArrayType: ""}, nil
	}
```
Without this part we failing test at `parser_test.go:1827` and `parser_test.go:1830` (testdata/simple3)

**Comment by sdghchj** [comment]
> > What does FuncTyp works for? @wsnotify
> 
> In master we have:
> 
> ```
> 	if _, ok := expr.(*ast.FuncType); ok { // if func()
> 		return propertyName{SchemaType: "func", ArrayType: ""}, nil
> 	}
> ```
> 
> Without this part we failing test at `parser_test.go:1827` and `parser_test.go:1830` (testdata/simple3)



> > What does FuncTyp works for? @wsnotify
> 
> In master we have:
> 
> ```
> 	if _, ok := expr.(*ast.FuncType); ok { // if func()
> 		return propertyName{SchemaType: "func", ArrayType: ""}, nil
> 	}
> ```
> 
> Without this part we failing test at `parser_test.go:1827` and `parser_test.go:1830` (testdata/simple3)

I found no FuncType members in testdata/simple3

**Comment by wsnotify** [comment]
> I found no FuncType members in testdata/simple3

testdata/simple3/web/handler.go:34
`	Function  func()`

**Comment by sdghchj** [comment]
> > I found no FuncType members in testdata/simple3
> 
> testdata/simple3/web/handler.go:34
> ` Function func()`

Sorry, I've still got an old branch.

**Comment by sdghchj** [comment]
@wsnotify Thank you for your contributions.
